name: smarthome
description: Controlling Smarthome devices with AppBroker.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.2.3+0

environment:
  sdk: '>=3.5.0 <4.0.0'
  
platforms:
  android:
  linux:
  macos:
  web:
  windows:

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: ^3.1.1
  collection: ^1.18.0
  device_info_plus: ^11.1.0
  encrypt: ^5.0.3
  equatable: ^2.0.3
  expandable: ^5.0.1
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.7
  format: ^1.5.2
  github: ^9.0.0
  http: ^1.2.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logging: ^1.2.0
  multicast_dns: ^0.3.2
  new_gradient_app_bar: ^0.2.0
  oktoast: ^3.3.1
  package_info_plus: ^8.0.2
  path: ^1.9.0
  quiver: ^3.0.1+1
  shared_preferences_web: ^2.0.3
  shared_preferences: ^2.0.13
  signalr_netcore: ^1.4.0
  syncfusion_flutter_charts: ^27.1.51
  syncfusion_flutter_core: ^27.1.51
  syncfusion_flutter_gauges: ^27.1.51
  tuple: ^2.0.0
  url_launcher_web: ^2.0.20
  url_launcher: ^6.0.20
  version: ^3.0.2
  hooks_riverpod: ^2.6.1
  flutter_hooks:
  riverpod_annotation: ^2.6.1
  chopper: ^8.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  archive : ^3.3.1
  build_runner: ^2.4.13
  crypto: ^3.0.6
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.0
  pointycastle: ^3.6.1
  custom_lint:
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1
  visibility_detector: ^0.4.0+2
  chopper_generator: ^8.0.1
  swagger_dart_code_generator: 
    git:
      url: https://github.com/airsphere-gmbh/swagger-dart-code-generator.git

global_options:
  json_serializable:
    runs_before:
      - retrofit_generator

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/vectors/
    - .git/HEAD         # This file points out the current branch of the project.
  fonts:
    - family:  Smarthome
      fonts:
        - asset: fonts/Smarthome.ttf
