name: smarthome
description: Controlling Smarthome devices with AppBroker.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.1.5+0

environment:
  sdk: '>=2.17.0 <3.0.0'
  
platforms:
  android:
  linux:
  macos:
  web:
  windows:

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: ^3.1.1
  charts_flutter: any
  collection: ^1.15.0
  date_time_picker: any
  equatable: ^2.0.3
  expandable: ^5.0.1
  flutter_local_notifications: ^9.3.2
  flutter_staggered_grid_view: ^0.6.1
  flutter_svg: ^1.0.3
  github: ^9.0.0
  http: ^0.13.4
  json_annotation: ^4.6.0
  multicast_dns: ^0.3.2
  new_gradient_app_bar: ^0.2.0
  package_info_plus: ^1.4.3
  quiver: ^3.0.1+1
  shared_preferences_web: ^2.0.3
  shared_preferences: ^2.0.13
  # signalr_core: ^1.1.1
  syncfusion_flutter_charts: ^20.2.40
  syncfusion_flutter_core: ^20.2.40
  syncfusion_flutter_gauges: ^20.2.40
  synchronized: ^3.0.0
  tuple: ^2.0.0
  url_launcher: ^6.0.20
  version: ^3.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  visibility_detector: ^0.3.3
  archive : ^3.3.1
  build_runner:
  flutter_lints:
  flutter_riverpod: 2.0.0-dev.8
  json_serializable: 
  signalr_netcore:
  crypto:
  encrypt:
  pointycastle: ^3.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/vectors/
    - .git/HEAD         # This file points out the current branch of the project.
    - .git/ORIG_HEAD    # This file points to the commit id at origin (last commit id of the remote repository).
  fonts:
    - family:  Smarthome
      fonts:
        - asset: fonts/Smarthome.ttf
