name: smarthome
description: Controlling Smarthome devices with AppBroker.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.1.4+0

environment:
  sdk: '>=2.12.0 <3.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
  # signalr_client:
  signalr_core: ^1.1.1
    # git:
    #   url: git://github.com/jamiewest/signalr_core.git
    # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  json_annotation: ^4.1.0 
  shared_preferences_web: ^2.0.0 
  # flutter_swiper:
  charts_flutter: ^0.11.0 
  syncfusion_flutter_charts: ^19.2.48
  # file_picker: 
  http: ^0.13.3
  adaptive_theme: ^2.2.0
  flutter_staggered_grid_view: ^0.4.0
  collection: ^1.15.0-nullsafety.4
  syncfusion_flutter_gauges: ^19.2.48
  date_time_picker: ^2.1.0
  equatable: ^2.0.3
  expandable: ^5.0.1
  new_gradient_app_bar: ^0.2.0
  flutter_svg: ^0.22.0
  url_launcher:
  multicast_dns: ^0.3.1
  version: ^2.0.0
  package_info_plus: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6 
  json_serializable: ^5.0.0 


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/vectors/
  fonts:
    - family:  Smarthome
      fonts:
        - asset: fonts/Smarthome.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
