// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-2VRykZ0hZVwh8-I7jqOVR_8tWwu0FIo',
    appId: '1:676052672736:web:f2eeb331cf7b65b0d3f085',
    messagingSenderId: '676052672736',
    projectId: 'smarthome-8582c',
    authDomain: 'smarthome-8582c.firebaseapp.com',
    storageBucket: 'smarthome-8582c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWDL8YkshmtuyecsKJ2_Q1eq3MBJGjIXg',
    appId: '1:676052672736:android:3d2a3ddb0a86f6a6d3f085',
    messagingSenderId: '676052672736',
    projectId: 'smarthome-8582c',
    storageBucket: 'smarthome-8582c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApL1meTPPvyFe5r_VUS1Mbr5JFNHIJJrg',
    appId: '1:676052672736:ios:52d0eab5daa03da8d3f085',
    messagingSenderId: '676052672736',
    projectId: 'smarthome-8582c',
    storageBucket: 'smarthome-8582c.appspot.com',
    iosBundleId: 'de.susch19.smarthome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApL1meTPPvyFe5r_VUS1Mbr5JFNHIJJrg',
    appId: '1:676052672736:ios:52d0eab5daa03da8d3f085',
    messagingSenderId: '676052672736',
    projectId: 'smarthome-8582c',
    storageBucket: 'smarthome-8582c.appspot.com',
    iosBundleId: 'de.susch19.smarthome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-2VRykZ0hZVwh8-I7jqOVR_8tWwu0FIo',
    appId: '1:676052672736:web:e6b0a957bf4c91cbd3f085',
    messagingSenderId: '676052672736',
    projectId: 'smarthome-8582c',
    authDomain: 'smarthome-8582c.firebaseapp.com',
    storageBucket: 'smarthome-8582c.appspot.com',
  );
}
